# Generated by Django 5.2.4 on 2025-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
